print("Please enter your name:")
name_tci=input ()
print ("Hello," , name_tci)
print ("What is your age?")
age_tci = input ()
print ("Please think of a number between 0 and", age_tci , "\n What number did you think of?")
number_tci = input ()
print ("I thought of" , number_tci , "too!")
